server:
  port: 1006

spring:
  application:
    name: config-server


  #访问的url对应能搜到的配置文件对应关系
  # application:应用名(spring.application.name)
  # profile:环境名(dev,test,prod)
  # label:分支名(master,dev,test)
  #
  #/{application}/{profile}[/{label}]
  #/{application}-{profile}.yml
  #/{label}/{application}-{profile}.yml
  #/{application}-{profile}.properties
  #/{label}/{application}-{profile}.properties

  #访问http://localhost:1006/config-server/dev/master
  #返回值写在result.json
  cloud:
      config:
        server:
          git:
            #配置git仓库地址
            uri: https://github.com/ClearLoveRNG/SpringCloud
            #访问git仓库的用户名
            username: ClearLoveRNG
            #访问git仓库的用户密码
            password: Jht19960726,.
            #配置仓库下的相对搜索位置
            search-paths: /config-server/src/main/resources
        #配置仓库的分支
        label: master







