server:
  port: 4444

#为eureka客户端命名
spring:
  application:
    name: ribbon

#指定eureka服务端(注册中心)的地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
    #服务消费者会定期(默认30秒)向注册中心获取服务清单
    registry-fetch-interval-seconds: 30